In [2]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [5]:
calo = A.sum(axis=0)#Tinh tong theo cot thay axis = 0 thi la tong theo dong
print(calo)

[ 59.  239.  155.4  76.9]


In [20]:
percent = 100*A/calo.reshape(1,4)

print(percent)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [22]:
B = np.array([[0,3,4],
              [2,6,4]])

print(B)

[[0 3 4]
 [2 6 4]]


In [25]:
print(np.linalg.norm(B, axis=1, keepdims=True))
# Tinh ||x||

[[5.        ]
 [7.48331477]]


In [23]:
 x_norm = B/np.linalg.norm(B, axis=1, keepdims=True)

In [24]:
print(x_norm)

[[0.         0.6        0.8       ]
 [0.26726124 0.80178373 0.53452248]]


In [ ]:
# -----Test-----
# a=np.random.randn(3,3)
# print(a)
# b = np.random.randn(3, 3)
# print(b)
# c = a*b 
# print(c)

# a.shape=(3,3)
# print(a)
# b.shape = (3, 3)
# print(b)
# c = a**2 + b.T**2

# print(c)